### ISSUE TITLE
leaked secrets in history

### ISSUE THREAD

**Issue by 0xdarkman** [Rasmoat001/RasmoatMM#1]
https://github.com/Rasmoat001/RasmoatMM/blob/7573a502857b6a8bc49b4d08dc3634ba70236284/config.py

**Comment by Rasmoat001** [comment]
Hey thanks man.. though they dont have withdrawal permission.. il make this private

**Comment by 0xdarkman** [comment]
no worries. i am glad i helped. disabled withdrawal permissions does not protect your funds. it can be obeyed.

**Comment by Rasmoat001** [comment]
Well then if anyone can withdraw funds through so then its binance fault i guess

**Comment by 0xdarkman** [comment]
https://www.infoguardsecurity.com/how-cybercriminals-steal-millions-using-api-keys/

**Comment by Rasmoat001** [comment]
hmm impressive..
